### ISSUE TITLE
[gRPC] ArchiveSketchReq cannot override existing archives

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#1160]
### Current behavior

This is a follow-up of https://github.com/arduino/arduino-cli/pull/931.

I want to archive a sketch with the gRPC API. It works, but I cannot override existing archives.

```
root ERROR Uncaught Exception:  Error: 2 UNKNOWN: archive already exists
root ERROR Error: 2 UNKNOWN: archive already exists
    at Object.callErrorFromStatus (/Users/akos.kitta/git/arduino-editor/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/akos.kitta/git/arduino-editor/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/Users/akos.kitta/git/arduino-editor/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334:141)
    at Object.onReceiveStatus (/Users/akos.kitta/git/arduino-editor/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)
    at /Users/akos.kitta/git/arduino-editor/node_modules/@grpc/grpc-js/build/src/call-stream.js:129:78
```

The Java IDE can override existing sketches, so we need this functionality on the CLI too. Please support `forceOverride` Thank you!

### Environment

- CLI version (output of `arduino-cli version`): 0.15.0-rc1
- OS and platform:

**Comment by per1234** [comment]
This also occurs when using `arduino-cli sketch archive` via the command line:

```text
$ arduino-cli version
arduino-cli.exe  Version: nightly-20220331 Commit: 38ebf64 Date: 2022-03-31T01:34:02Z

$ arduino-cli sketch archive

$ arduino-cli sketch archive
Error archiving: Archive already exists
```
