### ISSUE TITLE
Invalid argument when running arduino-cli-upload

### ISSUE THREAD

**Issue by chmanie** [arduino/arduino-cli#1399]
### Current behavior

When I run the following command I get the error that `esptool` couldn't be executed:

```
❯ arduino-cli upload --port /dev/tty.usbserial-1410 --fqbn esp32:esp32:nodemcu-32s MyFirstSketch
esptool.py v3.0-dev
Serial port /dev/tty.usbserial-1410
Traceback (most recent call last):
  File "esptool.py", line 3969, in <module>
  File "esptool.py", line 3962, in _main
  File "esptool.py", line 3551, in main
  File "esptool.py", line 271, in __init__
  File "serial/__init__.py", line 88, in serial_for_url
  File "serial/serialposix.py", line 272, in open
  File "serial/serialposix.py", line 438, in _reconfigure_port
termios.error: (22, 'Invalid argument')
Failed to execute script esptool
Error during Upload: uploading error: uploading error: exit status 255
```

### Expected behavior

The upload succeeds.

### Environment

- CLI version (output of `arduino-cli version`): `arduino-cli alpha Version: 0.18.3 Commit: d710b642 Date: 2021-05-21T17:11:27Z`
- OS and platform: I'm on a Mac (11.5.2) and installed arduino-cli using homebrew.

**Comment by silvanocerza** [comment]
This doesn't seem like an Arduino CLI issue to me. 

The `esptool.py` upload tool is failing not the CLI, you should probably report this issue on the esp32 repo. 
https://github.com/espressif/arduino-esp32
