### ISSUE TITLE
arduino-cli board details [RUNTIME ERROR]

### ISSUE THREAD

**Issue by tammarop** [arduino/arduino-cli#178]
I have noticed an error with the command "arduino-cli board details"

```
arduino-cli board details arduino:avr:uno 
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/arduino/arduino-cli/output.(*Table).Render(0xc42017f9f0, 0xc42017faf0, 0x4)
	/home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/output/table.go:111 +0x739
github.com/arduino/arduino-cli/commands/board.(*boardDetails).EmitTerminal(0xc4203682c0, 0x0, 0x4954ca0)
	/home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/commands/board/details.go:147 +0x7de
github.com/arduino/arduino-cli/output.Emit(0x46659a0, 0xc4203682c0)
	/home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/output/output.go:49 +0xf8
github.com/arduino/arduino-cli/commands/board.runDetailsCommand(0xc420161680, 0xc42008b5e0, 0x1, 0x1)
	/home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/commands/board/details.go:88 +0x890
github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc420161680, 0xc42008b5a0, 0x1, 0x1, 0xc420161680, 0xc42008b5a0)
	/home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420160f00, 0xc4201aa000, 0xc4201a4a00, 0xc4201a4280)
	/home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420160f00, 0x44d16fc, 0xc42017ff78)
	/home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/main.go:30 +0x27
```

This command works without exceptions if you add "--format json"
```
arduino-cli board details arduino:avr:uno --format json
{
  "Name": "Arduino/Genuino Uno",
  "ConfigOptions": [],
  "RequiredTools": [
    {
      "ToolName": "avr-gcc",
      "ToolVersion": "5.4.0-atmel3.6.1-arduino2",
      "ToolPackager": "arduino"
    },
    {
      "ToolName": "avrdude",
      "ToolVersion": "6.3.0-arduino14",
      "ToolPackager": "arduino"
    },
    {
      "ToolName": "arduinoOTA",
      "ToolVersion": "1.2.1",
      "ToolPackager": "arduino"
    }
  ]
}
```
arduino-cli version is the 0.3.6-alpha.preview
OS: mac os x 10.11.6

**Comment by per1234** [comment]
I was able to reproduce this error on Linux with arduino-cli 0.3.6-alpha.preview, but not when using a build of arduino-cli from the tip of the master branch. For this reason, I'm going to assume the issue has already been fixed by https://github.com/arduino/arduino-cli/commit/87c5e18c699de2fad6590762b53690794695e020
