### ISSUE TITLE
panic when compiling keyboard.io Model01 firmware on Void Linux

### ISSUE THREAD

**Issue by non-Jedi** [arduino/arduino-cli#192]
~/.arduino15/arduino-cli.yaml :

```yaml
proxy_type: auto
sketchbook_path: /home/adam/Arduino
arduino_data: /home/adam/.arduino15
board_manager:
  additional_urls:
    - https://raw.githubusercontent.com/keyboardio/boardsmanager/master/package_keyboardio_index.json
```

Commands to reproduce:

```
arduino-cli core update-index
arduino-cli core install keyboardio:avr
git clone https://github.com/keyboardio/Model01-Firmware.git
arduino-cli compile -b keyboardio:avr:model01 Model01-Firmware/Model01-Firmware.ino
```

The arduino-cli executable used is from the Void Linux package repository: `arduino-cli version 0.3.6-alpha.preview`.

Debug output on `arduino-cli compile -b keyboardio:avr:model01 Model01-Firmware/Model01-Firmware.ino`:

```
INFO[0000] Checking for config file in: /home/adam/.arduino15/arduino-cli.yaml 
INFO[0000] Reading configuration from /home/adam/.arduino15/arduino-cli.yaml 
INFO[0000] Checking if CLI is Bundled into the IDE      
INFO[0000] Candidate IDE Directory: /usr/bin            
INFO[0000] CLI is not bundled into the IDE              
INFO[0000] Checking for config in: /arduino-cli.yaml    
INFO[0000] error loading                                 error="open /arduino-cli.yaml: no such file or directory"
INFO[0000] Checking for config in: /home/arduino-cli.yaml 
INFO[0000] error loading                                 error="open /home/arduino-cli.yaml: no such file or directory"
INFO[0000] Checking for config in: /home/adam/arduino-cli.yaml 
INFO[0000] error loading                                 error="open /home/adam/arduino-cli.yaml: no such file or directory"
INFO[0000] Checking for config in: /home/adam/repos/arduino-cli.yaml 
INFO[0000] error loading                                 error="open /home/adam/repos/arduino-cli.yaml: no such file or directory"
INFO[0000] Checking for config in: /home/adam/repos/Model01-Firmware/arduino-cli.yaml 
INFO[0000] error loading                                 error="open /home/adam/repos/Model01-Firmware/arduino-cli.yaml: no such file or directory"
INFO[0000] Configuration set                            
INFO[0000] arduino-cli-0.3.6-alpha.preview              
INFO[0000] Starting root command preparation (`arduino`) 
INFO[0000] Formatter set                                
INFO[0000] Calling version command on `arduino`         
arduino-cli version 0.3.6-alpha.preview
adam: [Model01-Firmware] $ arduino-cli version
arduino-cli version 0.3.6-alpha.preview
adam: [Model01-Firmware] $ arduino-cli version 0.3.6-alpha.preview^C
adam: [Model01-Firmware] $ arduino-cli --debug compile -b keyboardio:avr:model01 Model01-Firmware.ino 
INFO[0000] Checking for config file in: /home/adam/.arduino15/arduino-cli.yaml 
INFO[0000] Reading configuration from /home/adam/.arduino15/arduino-cli.yaml 
INFO[0000] Checking if CLI is Bundled into the IDE      
INFO[0000] Candidate IDE Directory: /usr/bin            
INFO[0000] CLI is not bundled into the IDE              
INFO[0000] Checking for config in: /arduino-cli.yaml    
INFO[0000] error loading                                 error="open /arduino-cli.yaml: no such file or directory"
INFO[0000] Checking for config in: /home/arduino-cli.yaml 
INFO[0000] error loading                                 error="open /home/arduino-cli.yaml: no such file or directory"
INFO[0000] Checking for config in: /home/adam/arduino-cli.yaml 
INFO[0000] error loading                                 error="open /home/adam/arduino-cli.yaml: no such file or directory"
INFO[0000] Checking for config in: /home/adam/repos/arduino-cli.yaml 
INFO[0000] error loading                                 error="open /home/adam/repos/arduino-cli.yaml: no such file or directory"
INFO[0000] Checking for config in: /home/adam/repos/Model01-Firmware/arduino-cli.yaml 
INFO[0000] error loading                                 error="open /home/adam/repos/Model01-Firmware/arduino-cli.yaml: no such file or directory"
INFO[0000] Configuration set                            
INFO[0000] arduino-cli-0.3.6-alpha.preview              
INFO[0000] Starting root command preparation (`arduino`) 
INFO[0000] Formatter set                                
INFO[0000] Executing `arduino compile`                  
INFO[0000] Initializing package manager                 
INFO[0000] Loading hardware from: /home/adam/.arduino15/packages 
INFO[0000] Loading package arduino from: /home/adam/.arduino15/packages/arduino 
INFO[0000] Checking existence of 'tools' path: /home/adam/.arduino15/packages/arduino/tools 
INFO[0000] Loading tools from dir: /home/adam/.arduino15/packages/arduino/tools 
INFO[0000] Loaded tool                                   tool="arduino:avr-gcc@4.8.1-arduino5"
INFO[0000] Loaded tool                                   tool="arduino:avrdude@6.0.1-arduino5"
INFO[0000] Loading package builtin from: /home/adam/.arduino15/packages/builtin 
INFO[0000] Checking existence of 'tools' path: /home/adam/.arduino15/packages/builtin/tools 
INFO[0000] Loading tools from dir: /home/adam/.arduino15/packages/builtin/tools 
INFO[0000] Loaded tool                                   tool="builtin:ctags@5.8-arduino11"
INFO[0000] Loading package keyboardio from: /home/adam/.arduino15/packages/keyboardio/hardware 
INFO[0000] Loaded platform                               platform="keyboardio:avr@1.94-beta"
Ts: 1554920892 - Running: GenerateBuildPathIfMissing
Setting build path to /tmp/arduino-sketch-53AC11F7037FA77FB94F54766164C803
Ts: 1554920892 - Running: EnsureBuildPathExists
Ts: 1554920892 - Running: ContainerSetupHardwareToolsLibsSketchAndProps
Ts: 1554920892 - Running: AddAdditionalEntriesToContext
Ts: 1554920892 - Running: FailIfBuildPathEqualsSketchPath
Ts: 1554920892 - Running: HardwareLoader
Ts: 1554920892 - Running: PlatformKeysRewriteLoader
Ts: 1554920892 - Running: RewriteHardwareKeys
Ts: 1554920892 - Running: TargetBoardResolver
Ts: 1554920892 - Running: ToolsLoader
INFO[0000] Searching tools required for board keyboardio:avr:model01 
INFO[0000] Required tool                                 tool="arduino:avr-gcc@4.8.1-arduino5"
INFO[0000] Required tool                                 tool="arduino:avrdude@6.0.1-arduino5"
Ts: 1554920892 - Running: AddBuildBoardPropertyIfMissing
Ts: 1554920892 - Running: LibrariesLoader
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x790c8e]

goroutine 1 [running]:
github.com/arduino/arduino-cli/arduino/cores.(*PlatformRelease).GetLibrariesDir(0x0, 0x0)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/arduino/cores/cores.go:210 +0x3e
github.com/arduino/arduino-cli/arduino/libraries/librariesmanager.(*LibrariesManager).AddPlatformReleaseLibrariesDir(0xc0000a5b00, 0x0, 0x4)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/arduino/libraries/librariesmanager/librariesmanager.go:138 +0x43
github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder.(*LibrariesLoader).Run(0xfb5708, 0xc000170e00, 0xfb5708, 0x0)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder/libraries_loader.go:62 +0x494
github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder.(*ContainerSetupHardwareToolsLibsSketchAndProps).Run(0xfb5708, 0xc000170e00, 0xfb5708, 0x0)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder/container_setup.go:63 +0x40a
github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder.runCommands(0xc000170e00, 0xc0001c5620, 0x22, 0x22, 0xa90e01, 0xc0001c54d8, 0x30)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder/builder.go:191 +0xdf
github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder.(*Builder).Run(0xc0001c5898, 0xc000170e00, 0x0, 0xb32ac0)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder/builder.go:109 +0xd5e
github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder.RunBuilder(...)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/vendor/github.com/arduino/arduino-builder/builder.go:207
github.com/arduino/arduino-cli/commands/compile.run(0xc000166280, 0xc0000a4c00, 0x1, 0x4)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/commands/compile/compile.go:240 +0x155d
github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000166280, 0xc0000a4bc0, 0x4, 0x4, 0xc000166280, 0xc0000a4bc0)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000145180, 0x93de5c, 0xc000163f88, 0xc000086058)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra/command.go:852 +0x2c0
github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /builddir/arduino-cli-0.3.6-alpha.preview/_build-arduino-cli-xbps/src/github.com/arduino/arduino-cli/main.go:30 +0x28
```

Building the `MyFirstSketch` shown in the README for `--fqbn arduino:samd:mkr1000` does not result in any error, so it's something specific about this core/sketch.

**Comment by per1234** [comment]
There is a bug in your command in that you are specifying a sketch file instead of the sketch folder (https://github.com/arduino/arduino-cli/issues/51) but that should result in a nice error like:
```
Error: copying output file: open Foo/Foo.ino/Foo.ino.arduino.samd.mkrzero.bin: not a directory
Error during build
```
So I think there is a bigger problem here.
